[package]
name = "opencode-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
eframe = "0.33.3"
egui = "0.33.3"
egui-dropdown = "0.14.0"
egui_flex = "0.5.0"
env_logger = "0.11.8"
libc = "0.2.180"
tokio = { version = "1.49.0", features = ["rt"] }
