[package]
name = "opencode-gui"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
eframe = "0.33.3"
egui = "0.33.3"
egui-dropdown = "0.14.0"
egui_flex = "0.5.0"
egui_inbox = "0.10.0"
egui_taffy = "0.10.0"
env_logger = "0.11.8"
log = "0.4"
libc = "0.2.180"
reqwest = { version = "0.13.1", features = ["json"] }
serde = "1.0.228"
serde_json = "1.0.149"
tokio = { version = "1.49.0", features = ["rt", "rt-multi-thread", "macros"] }
